const systemRoot = document.querySelector('[data-system-page]');
const systemPage = systemRoot?.dataset.systemPage;
let systemData = null;
let systemToastTimer;

const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const statusClass = (value) => ({ 启用: 'green', 禁用: 'gray', 草稿: 'gray', 已保存: 'green', 有效: 'green' }[value] || 'gray');
const tag = (value) => `<span class="tag ${statusClass(value)}">${escapeHtml(value)}</span>`;
function showToast(message) { const element = document.querySelector('[data-system-toast]'); if (!element) return; element.textContent = message; element.hidden = false; clearTimeout(systemToastTimer); systemToastTimer = setTimeout(() => { element.hidden = true; }, 2800); }
function closeDialog() { document.querySelector('[data-system-dialog]')?.remove(); }
function openDialog(title, subtitle, body, actions = '<button type="button" class="button" data-dialog-close>关闭</button>') { closeDialog(); const dialog = document.createElement('dialog'); dialog.className = 'system-dialog'; dialog.dataset.systemDialog = 'true'; dialog.innerHTML = `<div class="system-dialog-card"><div class="system-dialog-header"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(subtitle)}</p></div><button type="button" class="icon-button" data-dialog-close title="关闭" aria-label="关闭">×</button></div>${body}<div class="system-dialog-actions">${actions}</div></div>`; document.body.append(dialog); dialog.showModal(); return dialog; }
function pageFrame(title, description, controls, content) { if (!systemRoot) return; systemRoot.innerHTML = `<div class="system-page"><div class="page-head"><div><h1>${title}</h1><p>${description}</p></div>${controls || ''}</div>${content}<div class="toast" data-system-toast role="status" aria-live="polite" hidden></div></div>`; }
function field(label, name, type = 'text', placeholder = '', wide = false, value = '') { return `<label class="form-field${wide ? ' wide' : ''}"><span>${label}</span><input type="${type}" name="${name}" placeholder="${placeholder}" value="${escapeHtml(value)}"></label>`; }
function select(label, name, options, wide = false, all = true) { return `<label class="form-field${wide ? ' wide' : ''}"><span>${label}</span><select name="${name}">${all ? `<option value="">全部${label}</option>` : ''}${options.map((item) => `<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join('')}</select></label>`; }
function filterPanel(id, fields) { return `<div class="filter-panel" data-filter-drawer-shell="${id}"><button type="button" class="button filter-drawer-trigger" data-filter-drawer-trigger="${id}" aria-expanded="false" aria-controls="${id}"><span class="filter-trigger-icon" aria-hidden="true"></span>筛选条件</button><div class="filter-drawer-backdrop" data-filter-drawer-backdrop="${id}" hidden></div><form class="card filter-form" id="${id}"><div class="filter-head"><strong>筛选条件</strong><span>当前仅展示原型数据</span><button type="button" class="icon-button filter-drawer-close" data-filter-drawer-close="${id}" title="关闭筛选条件" aria-label="关闭筛选条件">×</button></div><div class="filter-grid system-filter-grid">${fields}</div><div class="filter-actions"><button type="reset" class="button">重置</button><button type="submit" class="button primary">查询</button></div></form></div>`; }
function table(head) { return `<div class="table-wrap system-table"><table>${head}<tbody class="table-body"></tbody></table></div><div class="pagination-bar"><span class="result-count">—</span><button class="button" disabled>上一页</button><button class="button primary">1</button><button class="button" disabled>下一页</button></div>`; }
function metrics(items) { return `<div class="card-grid compact-metrics">${items.map(([label, value, note]) => `<div class="card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`).join('')}</div>`; }
function renderRows(rows, template) { const body = systemRoot.querySelector('.table-body'); if (!body) return; body.innerHTML = rows.length ? rows.map((row) => `<tr data-row-id="${escapeHtml(row.id)}">${template(row)}</tr>`).join('') : '<tr><td colspan="20"><div class="empty">暂无符合条件的数据。</div></td></tr>'; const count = systemRoot.querySelector('.result-count'); if (count) count.textContent = `共 ${rows.length} 条`; }
function bindFilter(id, source, predicate, template) { document.querySelector(`#${id}`)?.addEventListener('submit', (event) => { event.preventDefault(); renderRows(source.filter(predicate(event.currentTarget)), template); }); document.querySelector(`#${id}`)?.addEventListener('reset', () => setTimeout(() => renderRows(source, template), 0)); }

const users = [
  { id: 'user-li', name: '李教务', account: 'jw_admin', phone: '138****2026', role: '教务主管', status: '启用', lastLogin: '2026-09-08 08:42', ip: '10.0.1.26' },
  { id: 'user-zhou', name: '周教研', account: 'research_01', phone: '139****3098', role: '教研主管', status: '启用', lastLogin: '2026-09-07 17:21', ip: '10.0.1.18' },
  { id: 'user-chen', name: '陈财务', account: 'finance_01', phone: '137****6812', role: '财务', status: '启用', lastLogin: '2026-09-07 15:08', ip: '10.0.1.33' },
  { id: 'user-old', name: '赵运营', account: 'operator_old', phone: '136****0048', role: '课程顾问', status: '禁用', lastLogin: '—', ip: '—' }
];
const roles = [
  { id: 'role-super', name: '超级管理员', key: 'super_admin', description: '全局配置、系统运维', users: 2, modules: '全部模块', updated: '2026-09-01', status: '启用', preset: true },
  { id: 'role-research', name: '教研主管', key: 'research_lead', description: '课程质量、教师资质审核', users: 2, modules: '课程中心、师资证书审核', updated: '2026-09-06', status: '启用', preset: true },
  { id: 'role-academic', name: '教务主管', key: 'academic_lead', description: '教学调度、教务执行、物资管理', users: 3, modules: '教务、招生、师资、物资', updated: '2026-09-08', status: '启用', preset: true },
  { id: 'role-consultant', name: '课程顾问', key: 'course_consultant', description: '客户跟进、销售转化', users: 6, modules: '面授招生与CRM', updated: '2026-09-02', status: '启用', preset: true },
  { id: 'role-finance', name: '财务', key: 'finance', description: '财务核算、对账', users: 2, modules: '财务中心、商城订单', updated: '2026-09-04', status: '启用', preset: true }
];
const permissionGroups = [
  ['工作台', ['查看本人待办']], ['师资中心', ['查看', '档案维护', '证书审核']], ['课程中心', ['查看', '课程申报审核', '内容与资源管理']], ['商城运营', ['查看订单', '收款记录', '订单处理']], ['面授招生与CRM', ['线索与试听', '报名转化', '班级与订单处理']], ['物资中心', ['查看', '维护', '出入库', '台账导出']], ['教务执行监管', ['查看', '排班与执行', '结业复核']], ['财务中心', ['工资管理', '收款记录', '退款处理']], ['系统管理', ['用户管理', '角色权限', '参数配置']]
];
const settings = { platform: '湖北艺术职业学院继续教育', timezone: 'Asia/Shanghai（UTC+8）', defaultLessonMinutes: 90, homeworkDeadlineHours: 72, attendanceThreshold: 80, homeworkThreshold: 80, switches: { teacherApplication: true, anonymousConsultation: true, messageRetry: true, consultantTrial: true } };

function renderUsers() {
  systemData = users;
  pageFrame('后台用户管理', '管理后台账号、角色和登录状态；禁用后用户无法登录，历史业务数据保留。', '<button class="button primary" data-system-action="user-create">新增用户</button>', metrics([['用户总数', users.length, '后台账号'], ['启用', users.filter((u) => u.status === '启用').length, '可正常登录'], ['禁用', users.filter((u) => u.status === '禁用').length, '账号不可登录'], ['今日登录', users.filter((u) => u.lastLogin.startsWith('2026-09-08')).length, '按最后登录时间']]) + filterPanel('user-filter', select('用户状态', 'status', ['启用', '禁用']) + select('所属角色', 'role', ['超级管理员', '教研主管', '教务主管', '课程顾问', '财务']) + field('关键词', 'keyword', 'text', '姓名 / 账号 / 手机号', true)) + '<p class="system-note">用户列表按最后登录时间降序排列，从未登录账号置于末尾；涉及登录状态变化和密码重置的操作均需要二次确认。</p>' + table('<thead><tr><th>用户</th><th>登录账号</th><th>手机号</th><th>所属角色</th><th>状态</th><th>最后登录</th><th>最后登录 IP</th><th>操作</th></tr></thead>'));
  const row = (item) => `<td><div class="system-user-cell"><span class="system-avatar">${item.name.slice(0, 1)}</span><strong>${item.name}</strong></div></td><td>${item.account}</td><td>${item.phone}</td><td>${tag(item.role)}</td><td>${tag(item.status)}</td><td>${item.lastLogin}</td><td>${item.ip}</td><td class="action-cell"><button class="text-button" data-system-action="user-edit">编辑</button><button class="text-button" data-system-action="user-reset">重置密码</button><button class="text-button" data-system-action="user-toggle">${item.status === '启用' ? '禁用' : '启用'}</button><button class="text-button danger-link" data-system-action="user-delete">删除</button></td>`;
  renderRows(systemData, row);
  bindFilter('user-filter', systemData, (form) => { const { status, role, keyword } = form; return (item) => (!status.value || item.status === status.value) && (!role.value || item.role === role.value) && (!keyword.value.trim() || `${item.name}${item.account}${item.phone}`.includes(keyword.value.trim())); }, row);
}
function renderRoles() {
  systemData = roles;
  pageFrame('角色权限管理', '维护五种预置角色的菜单级可见权限，业务动作仍受权限矩阵和模块规则约束。', '<button class="button" data-system-action="role-create">新增角色</button>', metrics([['角色总数', roles.length, '当前预置角色'], ['启用角色', roles.filter((r) => r.status === '启用').length, '可分配给用户'], ['角色用户数', roles.reduce((sum, r) => sum + r.users, 0), '按角色汇总'], ['预置角色', roles.filter((r) => r.preset).length, 'V1 内置']]) + filterPanel('role-filter', field('关键词', 'keyword', 'text', '角色名称 / 标识', true)) + '<p class="system-note">V1 仅配置菜单级可见性；角色下仍有用户时不可删除，禁用角色后该角色下用户权限失效。</p>' + table('<thead><tr><th>角色名称</th><th>角色标识</th><th>角色说明</th><th>用户数</th><th>可用模块</th><th>最近更新</th><th>状态</th><th>操作</th></tr></thead>'));
  const row = (item) => `<td><strong>${item.name}</strong>${item.preset ? '<br><span class="muted">系统预置</span>' : ''}</td><td>${item.key}</td><td>${item.description}</td><td>${item.users}</td><td>${item.modules}</td><td>${item.updated}</td><td>${tag(item.status)}</td><td class="action-cell"><button class="text-button" data-system-action="role-edit">编辑</button><button class="text-button" data-system-action="role-permission">权限分配</button><button class="text-button" data-system-action="role-toggle">${item.status === '启用' ? '禁用' : '启用'}</button><button class="text-button danger-link" data-system-action="role-delete">删除</button></td>`;
  renderRows(systemData, row);
  bindFilter('role-filter', systemData, (form) => { const keyword = form.keyword.value.trim(); return (item) => !keyword || `${item.name}${item.key}`.includes(keyword); }, row);
}
function renderSettings() {
  pageFrame('参数配置', '维护平台基础参数、教务默认值和业务开关；保存前校验数值范围。', '<button class="button primary" data-system-action="settings-save">保存修改</button>', `<form id="settings-form"><div class="settings-layout"><section class="card settings-card"><h2>平台基础参数</h2><div class="form-grid">${field('平台名称', 'platform', 'text', '', false, settings.platform)}<label class="form-field"><span>默认时区</span><select name="timezone"><option>${settings.timezone}</option></select></label>${field('默认课时时长（分钟）', 'defaultLessonMinutes', 'number', '30-240', false, settings.defaultLessonMinutes)}${field('作业默认截止时间（小时）', 'homeworkDeadlineHours', 'number', '1-720', false, settings.homeworkDeadlineHours)}${field('最低出勤率（%）', 'attendanceThreshold', 'number', '0-100', false, settings.attendanceThreshold)}${field('最低作业提交率（%）', 'homeworkThreshold', 'number', '0-100', false, settings.homeworkThreshold)}</div><p class="ops-form-help">结业判定使用最低出勤率和最低作业提交率，待补录考勤不参与计算。</p></section><section class="card settings-card"><h2>业务开关</h2><div class="settings-switches"><label class="settings-switch"><span>启用教师端课程申报</span><span class="switch"><input type="checkbox" name="teacherApplication" ${settings.switches.teacherApplication ? 'checked' : ''}><i class="switch-track"></i></span></label><label class="settings-switch"><span>启用学员端匿名咨询</span><span class="switch"><input type="checkbox" name="anonymousConsultation" ${settings.switches.anonymousConsultation ? 'checked' : ''}><i class="switch-track"></i></span></label><label class="settings-switch"><span>启用消息失败自动重试</span><span class="switch"><input type="checkbox" name="messageRetry" ${settings.switches.messageRetry ? 'checked' : ''}><i class="switch-track"></i></span></label><label class="settings-switch"><span>允许课程顾问登记试听</span><span class="switch"><input type="checkbox" name="consultantTrial" ${settings.switches.consultantTrial ? 'checked' : ''}><i class="switch-track"></i></span></label></div></section></div><div class="form-actions"><button type="submit" class="button primary">保存修改</button></div></form>`);
  document.querySelector('#settings-form')?.addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const lesson = Number(form.get('defaultLessonMinutes')); const deadline = Number(form.get('homeworkDeadlineHours')); const attendance = Number(form.get('attendanceThreshold')); const homeworkRate = Number(form.get('homeworkThreshold')); if (lesson < 30 || lesson > 240 || deadline < 1 || deadline > 720 || attendance < 0 || attendance > 100 || homeworkRate < 0 || homeworkRate > 100) { showToast('请检查参数范围：课时30-240分钟，截止时间1-720小时，阈值0-100%。'); return; } settings.platform = form.get('platform'); settings.defaultLessonMinutes = lesson; settings.homeworkDeadlineHours = deadline; settings.attendanceThreshold = attendance; settings.homeworkThreshold = homeworkRate; Object.keys(settings.switches).forEach((key) => { settings.switches[key] = form.get(key) === 'on'; }); showToast('参数配置已保存，变更将记录审计日志。'); });
}

function openUserForm(row) { return openSimpleForm(row ? '编辑后台用户' : '新增后台用户', '账号、角色和状态变更会影响后台登录与菜单可见性。', field('用户姓名', 'name', 'text', '请输入姓名') + field('登录账号', 'account', 'text', '请输入唯一账号') + field('手机号', 'phone', 'text', '请输入手机号') + select('所属角色', 'role', ['超级管理员', '教研主管', '教务主管', '课程顾问', '财务'], false, false) + select('用户状态', 'status', ['启用', '禁用'], false, false) + field('初始密码', 'password', 'password', row ? '留空则不修改' : '请输入初始密码'), (form) => { if (!String(form.get('name') || '').trim() || !String(form.get('account') || '').trim() || !String(form.get('role') || '').trim()) { showToast('姓名、登录账号和所属角色为必填项。'); return; } closeDialog(); showToast(row ? '用户信息已保存。' : '用户已创建，初始密码将通过安全渠道通知。'); }); }
function openSimpleForm(title, subtitle, body, onSubmit) { const dialog = openDialog(title, subtitle, `<form id="system-form" class="system-dialog-grid">${body}</form>`, '<button type="button" class="button" data-dialog-close>取消</button><button type="submit" form="system-form" class="button primary">确认</button>'); dialog.querySelector('#system-form')?.addEventListener('submit', (event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget), dialog); }); return dialog; }
function handleAction(action, row) {
  if (action === 'user-create' || action === 'user-edit') return openUserForm(row);
  if (action === 'user-reset') { const dialog = openDialog('确认重置密码', '新密码将通过安全渠道发送至用户手机。', `<p>确认重置“${escapeHtml(row.name)}”的登录密码？原密码将立即失效。</p>`, '<button type="button" class="button" data-dialog-close>取消</button><button type="button" class="button primary" data-confirm-action="user-reset">确认重置</button>'); dialog.dataset.rowId = row.id; return dialog; }
  if (action === 'user-toggle') { const target = row.status === '启用' ? '禁用' : '启用'; const dialog = openDialog(`确认${target}用户`, target === '禁用' ? '禁用后用户将无法登录，历史业务数据保留。' : '启用后用户可以重新登录后台。', `<p>确认${target}“${escapeHtml(row.name)}”？</p>`, `<button type="button" class="button" data-dialog-close>取消</button><button type="button" class="button primary" data-confirm-action="user-toggle">确认${target}</button>`); dialog.dataset.rowId = row.id; return dialog; }
  if (action === 'user-delete') { const dialog = openDialog('确认删除用户', '此操作不可恢复；业务数据和审计记录不会被删除。', `<p class="system-danger">确认删除“${escapeHtml(row.name)}”账号？建议优先禁用账号，避免误删仍被业务引用的用户。</p>`, '<button type="button" class="button" data-dialog-close>取消</button><button type="button" class="button danger-button" data-confirm-action="user-delete">确认删除</button>'); dialog.dataset.rowId = row.id; return dialog; }
  if (action === 'role-create' || action === 'role-edit') return openSimpleForm(action === 'role-create' ? '新增角色' : '编辑角色', '角色用于菜单级可见性控制，业务动作仍按权限矩阵执行。', field('角色名称', 'name', 'text', '请输入角色名称') + field('角色标识', 'key', 'text', '请输入唯一标识') + field('角色说明', 'description', 'text', '请输入职责说明', true) + select('角色状态', 'status', ['启用', '禁用'], false, false), () => { closeDialog(); showToast('角色信息已保存。'); });
  if (action === 'role-permission') return openPermissionDialog(row);
  if (action === 'role-toggle') { const target = row.status === '启用' ? '禁用' : '启用'; const dialog = openDialog(`确认${target}角色`, target === '禁用' ? '禁用后该角色下用户权限立即失效。' : '启用后该角色可继续分配给后台用户。', `<p>确认${target}角色“${escapeHtml(row.name)}”？</p>`, `<button type="button" class="button" data-dialog-close>取消</button><button type="button" class="button primary" data-confirm-action="role-toggle">确认${target}</button>`); dialog.dataset.rowId = row.id; return dialog; }
  if (action === 'role-delete') { if (row.users > 0) return openDialog('无法删除角色', '删除前需要转移该角色下的用户。', `<p class="system-danger">该角色下仍有 ${row.users} 名用户，请先转移用户后再操作。</p>`); const dialog = openDialog('确认删除角色', '删除后角色记录不可恢复。', `<p>确认删除角色“${escapeHtml(row.name)}”？</p>`, '<button type="button" class="button" data-dialog-close>取消</button><button type="button" class="button danger-button" data-confirm-action="role-delete">确认删除</button>'); dialog.dataset.rowId = row.id; return dialog; }
}
function openPermissionDialog(row) { const body = `<div class="permission-groups">${permissionGroups.map(([group, items]) => `<section class="permission-group"><h3>${group}</h3><div class="permission-items">${items.map((item, index) => `<label class="permission-item"><input type="checkbox" ${row.name === '超级管理员' || (row.name === '教务主管' && ['查看', '排班与执行', '结业复核', '维护', '出入库', '台账导出'].includes(item)) ? 'checked' : ''} data-permission="${escapeHtml(group)}-${escapeHtml(item)}"><span>${item}</span></label>`).join('')}</div></section>`).join('')}</div>`; return openSimpleForm('权限分配', `为“${row.name}”配置菜单级可见权限。`, body, () => { closeDialog(); showToast('角色权限已保存，变更将记录审计日志。'); }); }

document.addEventListener('click', (event) => {
  if (!systemRoot) return;
  if (event.target.closest('[data-dialog-close]')) { closeDialog(); return; }
  const confirm = event.target.closest('[data-confirm-action]');
  if (confirm) { const dialog = confirm.closest('dialog'); const action = confirm.dataset.confirmAction; const row = systemData.find((item) => item.id === dialog?.dataset.rowId); if (action === 'user-reset' && row) { closeDialog(); showToast('密码已重置，通知已发送至用户安全联系方式。'); } if (action === 'user-toggle' && row) { row.status = row.status === '启用' ? '禁用' : '启用'; closeDialog(); renderUsers(); showToast(`用户已${row.status}。`); } if (action === 'user-delete' && row) { users.splice(users.findIndex((item) => item.id === row.id), 1); closeDialog(); renderUsers(); showToast('用户已删除。'); } if (action === 'role-toggle' && row) { row.status = row.status === '启用' ? '禁用' : '启用'; closeDialog(); renderRoles(); showToast(`角色已${row.status}。`); } if (action === 'role-delete' && row) { roles.splice(roles.findIndex((item) => item.id === row.id), 1); closeDialog(); renderRoles(); showToast('角色已删除。'); } return; }
  const button = event.target.closest('[data-system-action]'); if (!button) return; const action = button.dataset.systemAction; const rowElement = button.closest('tr[data-row-id]'); const row = rowElement ? systemData.find((item) => item.id === rowElement.dataset.rowId) : null; handleAction(action, row);
});
if (systemPage === 'users') renderUsers();
if (systemPage === 'roles') renderRoles();
if (systemPage === 'settings') renderSettings();
