import { relativePath } from './paths.js';

const teacherMain = document.querySelector('.mobile-main');
const teacherPath = location.pathname;
const teacherKey = 'hbyx-mini-teacher-demo';
const teacherDefaults = { lesson: { status: '待上课', started: false, goal: '', attendance: { '林知夏': '', '周予安': '已到' } }, application: '审核中', graduation: '可申请', salary: '已发布' };
let teacherState;
try { teacherState = { ...teacherDefaults, ...JSON.parse(sessionStorage.getItem(teacherKey) || '{}') }; } catch { teacherState = { ...teacherDefaults }; }
function saveTeacher() { sessionStorage.setItem(teacherKey, JSON.stringify(teacherState)); }
function tEsc(value) { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function tPill(text, tone = '') { return `<span class="mp-pill ${tone}">${tEsc(text)}</span>`; }
function tButton(text, attrs = '', cls = '') { return `<button class="mp-button ${cls}" ${attrs}>${tEsc(text)}</button>`; }
function tCard(content) { return `<section class="mp-card">${content}</section>`; }
function tStack(...content) { return `<div class="mp-stack">${content.join('')}</div>`; }
function tToast(message) { const node = document.createElement('div'); node.className = 'mp-toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 2200); }
function tLayout(content) { teacherMain.innerHTML = content; }
function renderSchedule() { tLayout(tStack(tCard(`<div class="mp-section-head"><h2>本周课表</h2>${tPill('2026年9月7日')}</div><p>今日 2 节课 · 授课教师：王玥</p>`), `<div class="mp-list"><a class="mp-item" href="/teacher/pages/class-detail.html"><div><strong>少儿舞蹈基础班 · 第8次课</strong><small>今天 09:00-10:30 · 综合楼302</small></div>${tPill(teacherState.lesson.status, teacherState.lesson.status === '上课中' ? 'amber' : 'gray')}</a><a class="mp-item" href="/teacher/pages/class-detail.html"><div><strong>中国舞身韵训练 · 第4次课</strong><small>今天 14:00-15:30 · 舞蹈楼201</small></div>${tPill('待上课', 'gray')}</a></div>`, tCard(`<h3>教学待办</h3><p>3 条考勤待补录 · 2 个班级待提交结业申请</p>`))); }
function renderLesson() { const allDone = Object.values(teacherState.lesson.attendance).every(Boolean); tLayout(tStack(tCard(`<div class="mp-pills">${tPill(teacherState.lesson.status, teacherState.lesson.started ? 'amber' : 'gray')}${tPill('2课时', 'gray')}</div><h2 style="margin-top:12px">少儿舞蹈基础班 · 第8次课</h2><p>2026-09-13 09:00-10:30 · 综合楼302</p><div class="mp-actions" style="margin-top:14px">${teacherState.lesson.started ? tButton('上课中', 'disabled', 'secondary') : tButton('开始上课', 'data-teacher-action="start"')}${tButton('结束上课', `data-teacher-action="end" ${teacherState.lesson.started ? '' : 'disabled'}`, 'secondary')}</div></div>`), tCard(`<div class="mp-field"><label for="lesson-goal">教学目标（结束课次前必填）</label><textarea id="lesson-goal" placeholder="请输入本课教学目标">${tEsc(teacherState.lesson.goal)}</textarea></div><div class="mp-actions" style="margin-top:12px">${tButton('保存教学目标', 'data-teacher-action="save-goal"', 'secondary')}</div>`), tCard(`<div class="mp-section-head"><h3>学员考勤</h3>${tPill(allDone ? '已完成' : '待登记', allDone ? 'green' : 'amber')}</div><div class="mp-list">${Object.entries(teacherState.lesson.attendance).map(([name, status]) => `<div class="mp-row"><div><strong>${tEsc(name)}</strong><div class="mp-muted">请假时必须填写理由</div></div><select class="teacher-attendance" data-student="${tEsc(name)}"><option value="">请选择</option>${['已到', '迟到', '请假', '缺勤'].map(item => `<option ${status === item ? 'selected' : ''}>${item}</option>`).join('')}</select></div>`).join('')}</div>`), tCard(`<h3>课后作业</h3><p>只填写作业文本和截止时间，批改只提供文本评语，不设置分数和等级。</p><div class="mp-actions" style="margin-top:12px">${tButton('发布作业', 'data-teacher-action="homework"', 'secondary')}${tButton('申请结业', 'data-teacher-action="graduation"', 'ghost')}</div>`))); }
function renderClasses() { tLayout(tStack(tCard(`<div class="mp-section-head"><h2>我的班级</h2>${tPill('3个班级')}</div><p>查看班级学员、课表和教学记录。</p>`), `<div class="mp-list"><a class="mp-item" href="/teacher/pages/class-detail.html"><div><strong>少儿舞蹈基础班</strong><small>20名学员 · 平均出勤率 92%</small></div>${tPill('进行中', 'green')}</a><a class="mp-item" href="/teacher/pages/class-detail.html"><div><strong>中国舞身韵训练</strong><small>16名学员 · 作业提交率 88%</small></div>${tPill('进行中', 'green')}</a></div>`)); }
function renderClassDetail() { tLayout(tStack(tCard(`<h2>少儿舞蹈基础班</h2><p>2026秋季班 · 王玥 · 龙泉校区</p><div class="mp-metric-grid" style="margin-top:14px"><div class="mp-metric"><strong>20</strong><span>学员人数</span></div><div class="mp-metric"><strong>92%</strong><span>平均出勤</span></div><div class="mp-metric"><strong>88%</strong><span>作业提交</span></div></div>`), tCard(`<h3>班级学员</h3><div class="mp-list" style="margin-top:10px"><div class="mp-item"><div><strong>林知夏</strong><small>出勤 92% · 作业 80%</small></div>${tPill('正常', 'green')}</div><div class="mp-item"><div><strong>周予安</strong><small>出勤 100% · 作业 100%</small></div>${tPill('正常', 'green')}</div></div>`), tCard(`<h3>最近教学记录</h3><p>第7次课 · 组合训练 · 教学目标已保存 · 作业已发布</p>`))); }
function renderApplications() { tLayout(tStack(tCard(`<div class="mp-section-head"><h2>课程申报</h2>${tButton('新建申报', 'data-teacher-action="new-application"', 'secondary')}</div><p>申报课程后由后台审核，状态独立于授课安排。</p>`), `<div class="mp-list"><a class="mp-item" href="/teacher/pages/application-detail.html"><div><strong>舞蹈基本功</strong><small>面授课程 · 舞蹈表演 · 总课时16</small></div>${tPill(teacherState.application, 'amber')}</a><div class="mp-item"><div><strong>音乐欣赏入门</strong><small>草稿 · 尚未提交</small></div>${tPill('草稿', 'gray')}</div></div>`)); }
function renderApplicationDetail() { tLayout(tStack(tCard(`${tPill(teacherState.application, 'amber')}<h2 style="margin-top:12px">舞蹈基本功</h2><p>面授课程 · 舞蹈表演 · 总课时16</p>`), tCard(`<div class="mp-form"><div class="mp-field"><label>课程简介</label><textarea>围绕基本功、身韵和组合训练建立系统化面授课程。</textarea></div><div class="mp-field"><label>课程信息</label><input value="舞蹈表演 · 面授 · 16课时" readonly></div></div><div class="mp-actions" style="margin-top:14px">${tButton('提交审核', 'data-teacher-action="submit-application"')}</div>`))); }
function renderSalary() { tLayout(tStack(tCard(`<div class="mp-metric-grid"><div class="mp-metric"><strong>¥10,800</strong><span>累计收入</span></div><div class="mp-metric"><strong>¥5,760</strong><span>最近月份</span></div><div class="mp-metric"><strong>60</strong><span>有效课时</span></div></div>`), `<div class="mp-list"><a class="mp-item" href="/teacher/pages/salary-detail.html"><div><strong>2026年7月</strong><small>有效课时 32课时 · 发放日期 08-05</small></div>${tPill('已发布', 'green')}<strong class="mp-price">¥5,760</strong></a><a class="mp-item" href="/teacher/pages/salary-detail.html"><div><strong>2026年6月</strong><small>有效课时 28课时 · 发放日期 07-05</small></div>${tPill('已发布', 'green')}<strong class="mp-price">¥5,040</strong></a></div>`)); }
function renderSalaryDetail() { tLayout(tStack(tCard(`${tPill('已发布', 'green')}<h2 style="margin-top:12px">2026年7月工资</h2><strong class="mp-price" style="display:block;margin-top:12px;font-size:24px">¥5,760.00</strong><p>发放日期：2026-08-05</p>`), tCard(`<h3>课时明细</h3><div class="mp-list" style="margin-top:10px"><div class="mp-row"><span>少儿舞蹈基础班 · 32课时 × ¥180</span><strong>¥5,760</strong></div></div><div class="mp-notice" style="margin-top:14px">仅展示后台已发布工资记录。</div>`))); }
function renderProfile() { tLayout(tStack(tCard(`<div class="mp-eyebrow">教师账号</div><h2 style="margin-top:8px">王玥</h2><p>舞蹈表演 · 副教授 · 湖北艺术职业学院</p>`), `<div class="mp-list"><a class="mp-item" href="/teacher/pages/certificates.html"><strong>我的证书</strong><span class="mp-link">2张 ›</span></a><a class="mp-item" href="/teacher/pages/contracts.html"><strong>我的合同</strong><span class="mp-link">1份待签署 ›</span></a><a class="mp-item" href="/teacher/pages/graduation.html"><strong>结业申请记录</strong><span class="mp-link">审核中 ›</span></a><a class="mp-item" href="/teacher/pages/profile-detail.html"><strong>个人档案</strong><span class="mp-link">查看 ›</span></a></div>`)); }
function renderSimplePage(title, body) { tLayout(tStack(tCard(`<h2>${title}</h2>${body}</section>`))); }
function bindTeacherEvents() { document.querySelectorAll('[data-teacher-action]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.teacherAction; if (action === 'start') { teacherState.lesson.started = true; teacherState.lesson.status = '上课中'; saveTeacher(); renderLesson(); tToast('已开始上课'); } if (action === 'save-goal') { teacherState.lesson.goal = document.querySelector('#lesson-goal').value.trim(); saveTeacher(); tToast(teacherState.lesson.goal ? '教学目标已保存' : '请输入教学目标'); } if (action === 'end') { const goal = teacherState.lesson.goal.trim(); const allDone = Object.values(teacherState.lesson.attendance).every(Boolean); if (!goal || !allDone) { tToast(!goal ? '结束上课前请填写教学目标' : '结束上课前请完成全部学员考勤'); return; } teacherState.lesson.status = '已完成'; saveTeacher(); renderLesson(); tToast('课次已结束，课时已计入工资'); } if (action === 'homework') tToast('作业发布表单已打开，提交后会推送至学员端'); if (action === 'graduation') location.href = relativePath('/teacher/pages/graduation.html'); if (action === 'submit-application') { teacherState.application = '审核中'; saveTeacher(); tToast('课程申报已提交审核'); } if (action === 'new-application') tToast('请填写课程名称、专业、课程类型、简介和总课时'); })); document.querySelectorAll('.teacher-attendance').forEach(select => select.addEventListener('change', event => { const name = event.target.dataset.student; const status = event.target.value; if (status === '请假') { const reason = window.prompt('请输入请假理由'); if (!reason?.trim()) { event.target.value = ''; tToast('请假理由不能为空'); return; } } teacherState.lesson.attendance[name] = status; saveTeacher(); tToast(`${name}考勤已更新`); })); }
if (teacherPath.endsWith('/index.html') || teacherPath.endsWith('/teacher/')) renderSchedule();
else if (teacherPath.endsWith('/class-detail.html')) renderLesson();
else if (teacherPath.endsWith('/classes.html')) renderClasses();
else if (teacherPath.endsWith('/applications.html')) renderApplications();
else if (teacherPath.endsWith('/application-detail.html')) renderApplicationDetail();
else if (teacherPath.endsWith('/salary.html')) renderSalary();
else if (teacherPath.endsWith('/salary-detail.html')) renderSalaryDetail();
else if (teacherPath.endsWith('/profile.html')) renderProfile();
else if (teacherPath.endsWith('/profile-detail.html')) renderSimplePage('个人档案', '<p>可编辑字段：手机号、邮箱、紧急联系人、收款信息和个人简介。</p>');
else if (teacherPath.endsWith('/certificates.html')) renderSimplePage('我的证书', '<p>教师资格证 · 审核通过 · 有效</p><p>艺术等级证书 · 待审核 · 有效</p>');
else if (teacherPath.endsWith('/contracts.html')) renderSimplePage('我的合同', '<p>2026年度合作协议 · 待签署</p><div class="mp-actions" style="margin-top:14px">' + tButton('阅读并签署', 'data-teacher-action="sign-contract"') + '</div>');
else if (teacherPath.endsWith('/contract-detail.html')) renderSimplePage('合同详情', '<p>请阅读合同全文，确认课时费、授课课程和有效期后完成手写签名。</p><div class="mp-actions" style="margin-top:14px">' + tButton('确认签署', 'data-teacher-action="sign-contract"') + '</div>');
else if (teacherPath.endsWith('/graduation.html')) renderSimplePage('结业申请', '<p>申请按学员提交，不能将整个班级直接标记为结业。</p><div class="mp-form" style="margin-top:14px"><div class="mp-field"><label for="graduation-comment">综合评语</label><textarea id="graduation-comment" placeholder="请输入综合评语"></textarea></div><div class="mp-field"><label for="growth-advice">成长建议</label><textarea id="growth-advice" placeholder="请输入成长建议"></textarea></div></div><div class="mp-actions" style="margin-top:14px">' + tButton('提交结业申请', 'data-teacher-action="submit-graduation"') + '</div>');
else if (teacherPath.endsWith('/graduation-detail.html')) renderSimplePage('结业详情', '<p>状态：审核中 · 按学员展示结业材料和补课要求。</p>');
bindTeacherEvents();
